### ISSUE TITLE
Prerequisites for Steps

### ISSUE THREAD

**Issue by newpathexchange** [vbandaru/spring-boot-demo-rest-api#1]
Tested on Ubuntu 22.04

Step 1:
sudo apt install maven
sudo apt install openjdk-17-jdk

Step 2:
sudo apt install docker.io
sudo usermod -a -G docker <linux_user>

Added daemon flag to run command
docker run -d -p 8080:8080 spring-boot-demo-rest-api:1.0

**Comment by vbandaru** [comment]
Good point. I added pre-reqs to Readme.md.

**Comment by vbandaru** [comment]
closeing
